apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: k8bit-test-nodejs-app-hpa
  namespace: production
  labels:
    app: k8bit-test-nodejs-app
    environment: production
    managed-by: k8bit
    scaleops.sh/policy: nodejs-web-app
  annotations:
    scaleops.sh/workload-type: "nodejs"
    scaleops.sh/scaling-mode: "fast"
    k8bit.io/cold-start-protocol: "enabled"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8bit-test-nodejs-app
  minReplicas: 2
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min